// <auto-generated />
namespace Siemens.SCM.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddReference : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReference));
        
        string IMigrationMetadata.Id
        {
            get { return "201505080657051_AddReference"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
